name: Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t ${{ secrets.idk044}}/${{ secrets.plmplm}}:latest
      - name: publish
        run: |
          docker login -u ${{ secrets.idk004}} -p ${{ secrets.dckr_pat_Pe7va7s6BzxxzyTLDMggCjqaFas}}
          docker push ${{ secrets.idk004}}/${{ secrets.plmplm}}:latest
